name: wearable_app
description: A Flutter application for wearable device data visualization
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  firebase_core: ^2.13.0
  cloud_firestore: ^4.7.1
  firebase_auth: ^4.6.1
  provider: ^6.0.5
  fl_chart: ^0.62.0
  intl: ^0.18.0
  google_maps_flutter: ^2.2.8
  shared_preferences: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
