// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-uS5eCkcY9ZbeTdLqNzr4ymV946PAESU',
    appId: '1:672419730697:web:8b1ad6f75e83e6e600afd8',
    messagingSenderId: '672419730697',
    projectId: 'sleep-system-7d563',
    authDomain: 'sleep-system-7d563.firebaseapp.com',
    databaseURL: 'https://sleep-system-7d563-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sleep-system-7d563.firebasestorage.app',
    measurementId: 'G-V9XPKQEMH5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_3-daB5E16hiYrdlJAFITMoVvYg0cEoc',
    appId: '1:672419730697:android:fd68fd856fd8a17200afd8',
    messagingSenderId: '672419730697',
    projectId: 'sleep-system-7d563',
    databaseURL: 'https://sleep-system-7d563-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sleep-system-7d563.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5euFN85kj2bxc2kyteMr1C-Yfoo6qQcc',
    appId: '1:672419730697:ios:74c51a8c963d24fc00afd8',
    messagingSenderId: '672419730697',
    projectId: 'sleep-system-7d563',
    databaseURL: 'https://sleep-system-7d563-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sleep-system-7d563.firebasestorage.app',
    androidClientId: '672419730697-u2fvuei2ufi0drdg0294jnpfusfkft5m.apps.googleusercontent.com',
    iosClientId: '672419730697-jsn5v0pq631jr0151gf0099uaibq7c51.apps.googleusercontent.com',
    iosBundleId: 'com.example.wearableApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5euFN85kj2bxc2kyteMr1C-Yfoo6qQcc',
    appId: '1:672419730697:ios:74c51a8c963d24fc00afd8',
    messagingSenderId: '672419730697',
    projectId: 'sleep-system-7d563',
    databaseURL: 'https://sleep-system-7d563-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sleep-system-7d563.firebasestorage.app',
    androidClientId: '672419730697-u2fvuei2ufi0drdg0294jnpfusfkft5m.apps.googleusercontent.com',
    iosClientId: '672419730697-jsn5v0pq631jr0151gf0099uaibq7c51.apps.googleusercontent.com',
    iosBundleId: 'com.example.wearableApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-uS5eCkcY9ZbeTdLqNzr4ymV946PAESU',
    appId: '1:672419730697:web:0a8993816de0f95700afd8',
    messagingSenderId: '672419730697',
    projectId: 'sleep-system-7d563',
    authDomain: 'sleep-system-7d563.firebaseapp.com',
    databaseURL: 'https://sleep-system-7d563-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sleep-system-7d563.firebasestorage.app',
    measurementId: 'G-CMQBX33SB8',
  );

}